[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
monitor_speed = 115200
; GỠ cái ESP32softPWM nếu bạn đã thêm trước đó
; lib_deps =

; Thêm đúng SoftPWM của Brett Hagman (kéo trực tiếp từ GitHub)
lib_deps = https://github.com/bhagman/SoftPWM.git

; (tuỳ chọn) để PIO tìm symbol tốt hơn
lib_ldf_mode = deep+
